---
title: "Dates"
author: "Anna"
date: "11/30/2022"
output: html_document
---

Setting things up:
```{r, message = FALSE}
rm(list=ls())
library(here)
library(tidyverse)
library(ggfortify)
```

Import data:
```{r}
DF <- read.csv(here("Data", "cap_color_data_final.csv"), stringsAsFactors = TRUE)
str(DF)
```

Pull out only the Lab values for 10/14, 10/20, and 11/3 before any light treatments
```{r}
dates <- DF[, c("L", "a", "b", "before_after", "date_collected")] %>%
  filter(DF$date_collected == "10/14/22" | DF$date_collected == "10/20/22" | DF$date_collected == "11/3/22") %>%
  subset(before_after != "after")
```

Reassign row numbers and fix outlier
```{r}
rownames(dates) = seq(length=nrow(dates))
dates[42,2] = 4
```


Create a model to look at changes in red pigment throughout Oct-Nov (a-value)
```{r}
model_a_before <- glm(a ~ date_collected, data = dates, family = gaussian)
autoplot(model_a_before, smooth.color = NA)
```
Create ANOVA
```{r}
anova(model_a_before, test = "Chisq")
```

```{r}
summary(model_a_before)
```

Plot
```{r}
ggplot(dates, aes(x = date_collected, y = a, color = date_collected)) +
  geom_point(size = 3, alpha = 0.3) +
  stat_summary(
    geom_point = "point",
    fun.y = "mean",
    shape = "diamond",
    size = 2
  ) +
  theme_bw() +
  xlab("Date collected") +
  ylab("a-value") +
  coord_flip()
```

Tukey
```{r}
modela_before_tukey <- aov(a ~ date_collected, data = dates)
TukeyHSD(modela_before_tukey, conf.level=.95) 
```

Significant loss of red pigment between 10/14/22 and 11/3/22 

